@startuml

package "com.wlu.CP670.fort7350_Project" {

class Exercise {
String name
EXERCISE_TYPE exerciseType
EXERCISE_TARGET exerciseTarget
ArrayList<Set> sets
URL videoLink
DateTime timestamp
}


EXERCISE_TARGET -- Exercise
EXERCISE_TYPE -- Exercise
Set -- Exercise
ExerciseData -- Exercise

interface IExerciseList.Presenter <<interface>> {
    ArrayList<ExerciseList> getExerciseList(ExerciseFilter)
    openExerciseEditor(Exercise)
    stop();
}


interface IExerciseList.View <<interface>> {
    displayExercisesByFilter(ExerciseFilter)
    updateProgressBar(int)
    showExerciseEditor(Exercise)
}

interface IExerciseData.Presenter <<interface>> {
    int addExercise(Exercise)
    Exercise getLastExercise()
    int deleteExercise(Exercise)
    int getExerciseByDate(DATE_RANGE)
    int updateExercise(Exercise)
}

interface IExerciseData.View <<interface>> {
    displaySetData(Exercise)
}

enum EXERCISE_TYPE {
    FREEWEIGHT
    MACHINE
    BODYWEIGHT
    RESISTANCE
}

ENUM EXERCISE_TARGET {
    BICEP
    TRICEP
    FOREARM
    WRIST
    FRONT_DELTOID
    REAR_DELTOID
    SIDE_DELTOID
    TRAPEZIUS
    LOWER_BACK
    UPPER_BACK
    LATS
    HAMSTRING
    QUADRICEP
    CALF
    GLUTEUS
}

enum ExerciseFilter{
    TYPE
    TARGET
}

enum ExerciseDetailFilter{
    TYPE
    TARGET
    DATE_RANGE
}

class Set{
int weight_lbs
int reps
int orderNumber

int addWeight()
int deleteWeight()
}

AsyncTask <|-- ExerciseData
ExerciseData <|--- IExerciseData

class ExerciseData{
    Exercise exercise

    Exercise getLastExerciseData()
    addExercise(Exercise)
    getExerciseDataByDate()
}

enum MEASUREMENT_UNIT{
    KGS
    LBS
}


@enduml