@startuml
:database: as Db
:User: as user
:XML: as xml

left to right direction

rectangle exercises {
(View History) as (history)
(Browse Exercises) as (browse)
(Select Exercise) as (select)
(Add set) as (add_set)
(Add weight) as (weight_add)
(Add reps) as (reps_add)
(Save exercise) as (save)
(Exercise) as (exercise)
(View summary) as summary


user -- (browse)
user -- (select)
user -- (add_set)
user -- (weight_add)
user -- (reps_add)
user -- (save)
user -- (history)
user -- summary

(add_set) <|-- (weight_add)
(add_set) <|-- (reps_add)
(add_set) --|> (exercise)

(select) -- exercise

(browse) ---- xml
(history) <|-- Db
(summary) <|--Db
(save) -- exercise
(exercise) --|> Db
}

rectangle tools{
(Import) as (import)
(Export) as (export)

user  -- (import)
(import) ---- xml
user -- (export)
(export) ---- xml
}
@enduml