package wlu.cp670.ExerciseLog.Models;


import android.os.Parcel;
import android.os.Parcelable;

import java.util.ArrayList;


/**
 * <h1>Exercise</h1>
 * Class that contains the name, type, target
 * and list of sets
 *
 * reference:
 *     https://www.androidhive.info/2011/11/android-sqlite-database-tutorial/
 *
 * @author Adam Fortier
 * @version 1.0
 * @since 2019-12-10
 */
public class Exercise implements Parcelable {

    private String name;
    private String exerciseType;
    private String exerciseTarget;
    private ArrayList<Set> sets = null;

    //constructor
    public Exercise(String name, String exerciseType, String exerciseTarget) {
        this.name = name;
        this.exerciseType = exerciseType;
        this.exerciseTarget = exerciseTarget;
        this.sets = new ArrayList<>();
    }

    //parcelable implementation
    protected Exercise(Parcel in) {
        name = in.readString();
        exerciseType = in.readString();
        exerciseTarget = in.readString();
    }

    public static final Creator<Exercise> CREATOR = new Creator<Exercise>() {
        @Override
        public Exercise createFromParcel(Parcel in) {
            return new Exercise(in);
        }

        @Override
        public Exercise[] newArray(int size) {
            return new Exercise[size];
        }
    };

    //getters and setters generated by Android Studio
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getExerciseType() {
        return exerciseType;
    }

    public void setExerciseType(String exerciseType) {
        this.exerciseType = exerciseType;
    }

    public String getExerciseTarget() {
        return exerciseTarget;
    }

    public void setExerciseTarget(String exerciseTarget) {
        this.exerciseTarget = exerciseTarget;
    }

    public ArrayList<Set> getSetList() {
        return sets;
    }

    public void addSetList(ArrayList<Set> setArrayList){
        this.sets = setArrayList;
    }

    public void addSet(Set set){
        this.sets.add(set);
    }

    //toString generated by Android Studio
    @Override
    public String toString() {
        return "Exercise{" +
                "name='" + name + '\'' +
                ", exerciseType='" + exerciseType + '\'' +
                ", exerciseTarget='" + exerciseTarget + '\'' +
                ", sets=" + sets +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(name);
        dest.writeString(exerciseType);
        dest.writeString(exerciseTarget);
    }
}
