package wlu.cp670.ExerciseLog.Models;

import android.os.Parcel;
import android.os.Parcelable;

/**
* <h1>Set</h1>
* Class that contains the weight, reps, order number
* and timestamp
*
*
* @author Adam Fortier
* @version 1.0
* @since 2019-12-10
*/
public class Set implements Parcelable {

    private double weight;
    private int reps;
    private int orderNumber;
    private String dateTime;

    //constructor generated by Android studio
    public Set(double weight, int reps, int orderNumber, String dateTime) {
        this.weight = weight;
        this.reps = reps;
        this.orderNumber = orderNumber;
        this.dateTime = dateTime;
    }
    public Set(double weight, int reps, int orderNumber) {
        this.weight = weight;
        this.reps = reps;
        this.orderNumber = orderNumber;
        this.dateTime = "";
    }

    protected Set(Parcel in) {
        weight = in.readDouble();
        reps = in.readInt();
        orderNumber = in.readInt();
        dateTime = in.readString();
    }

    public static final Creator<Set> CREATOR = new Creator<Set>() {
        @Override
        public Set createFromParcel(Parcel in) {
            return new Set(in);
        }

        @Override
        public Set[] newArray(int size) {
            return new Set[size];
        }
    };

    //getters and setters generated by Android studio
    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public int getReps() {
        return reps;
    }

    public void setReps(int reps) {
        this.reps = reps;
    }

    public int getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }

    //toString generated by Android Studio
    @Override
    public String toString() {
        return "Set{" +
                "weight=" + weight +
                ", reps=" + reps +
                ", orderNumber=" + orderNumber +
                ", dateTime = " + dateTime +
                '}';
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeDouble(weight);
        dest.writeInt(reps);
        dest.writeInt(orderNumber);
        dest.writeString(dateTime);
    }
}
