package wlu.cp670.fort7350_project.Models;


public class Set {

    private double weight;
    private int reps;
    private int orderNumber;
    private String dateTime;

    //constructor generated by Android studio
    public Set(double weight, int reps, int orderNumber, String dateTime) {
        this.weight = weight;
        this.reps = reps;
        this.orderNumber = orderNumber;
        this.dateTime = dateTime;
    }
    public Set(double weight, int reps, int orderNumber) {
        this.weight = weight;
        this.reps = reps;
        this.orderNumber = orderNumber;
        this.dateTime = "";
    }
    //getters and setters generated by Android studio
    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public int getReps() {
        return reps;
    }

    public void setReps(int reps) {
        this.reps = reps;
    }

    public int getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }

    //toString generated by Android Studio
    @Override
    public String toString() {
        return "Set{" +
                "weight=" + weight +
                ", reps=" + reps +
                ", orderNumber=" + orderNumber +
                ", dateTime = " + dateTime +
                '}';
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

}
